name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t pyactioncheck .

    - name: Use image to run Python program and check app versions to verify installation
      run: |
        pwd
        docker run --rm --name versioncheck -v "$PWD" pyactioncheck python version-check/versions.py
